site_name: My Documentation
site_url: https://yoshikawa-kohei.github.io/


theme:
  name: material
  language: ja

nav:
  - ホーム: index.md
  - About: about.md


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format